# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Auducator_v4.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 854)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(640, 480))
        self.tabWidget.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_9.sizePolicy().hasHeightForWidth())
        self.groupBox_9.setSizePolicy(sizePolicy)
        self.groupBox_9.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName("groupBox_9")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.groupBox_9)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_7 = QtWidgets.QLabel(self.groupBox_9)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_11.addWidget(self.label_7)
        self.pushButton = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_11.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_11.addWidget(self.pushButton_4)
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_9)
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_11.addWidget(self.pushButton_5)
        self.horizontalLayout_9.addWidget(self.groupBox_9)
        self.groupBox_10 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_10.sizePolicy().hasHeightForWidth())
        self.groupBox_10.setSizePolicy(sizePolicy)
        self.groupBox_10.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName("groupBox_10")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.groupBox_10)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_8 = QtWidgets.QLabel(self.groupBox_10)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_12.addWidget(self.label_8)
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_12.addWidget(self.pushButton_3)
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_12.addWidget(self.pushButton_6)
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox_10)
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_12.addWidget(self.pushButton_7)
        self.horizontalLayout_9.addWidget(self.groupBox_10)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.groupBox_12 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName("groupBox_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.groupBox_12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.listView_2 = QtWidgets.QListView(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_2.sizePolicy().hasHeightForWidth())
        self.listView_2.setSizePolicy(sizePolicy)
        self.listView_2.setObjectName("listView_2")
        self.verticalLayout_8.addWidget(self.listView_2)
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_30.addWidget(self.pushButton_2)
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_12)
        self.pushButton_8.setObjectName("pushButton_8")
        self.horizontalLayout_30.addWidget(self.pushButton_8)
        self.verticalLayout_8.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.label_10 = QtWidgets.QLabel(self.groupBox_12)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_7.addWidget(self.label_10)
        self.verticalLayout_7.addWidget(self.groupBox_12)
        self.groupBox_13 = QtWidgets.QGroupBox(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName("groupBox_13")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_13)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.listView_3 = QtWidgets.QListView(self.groupBox_13)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView_3.sizePolicy().hasHeightForWidth())
        self.listView_3.setSizePolicy(sizePolicy)
        self.listView_3.setObjectName("listView_3")
        self.verticalLayout_9.addWidget(self.listView_3)
        self.pushButton_16 = QtWidgets.QPushButton(self.groupBox_13)
        self.pushButton_16.setObjectName("pushButton_16")
        self.verticalLayout_9.addWidget(self.pushButton_16)
        self.horizontalLayout_8.addLayout(self.verticalLayout_9)
        self.label_11 = QtWidgets.QLabel(self.groupBox_13)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_8.addWidget(self.label_11)
        self.verticalLayout_7.addWidget(self.groupBox_13)
        self.horizontalLayout_10.addLayout(self.verticalLayout_7)
        self.groupBox_11 = QtWidgets.QGroupBox(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_11.sizePolicy().hasHeightForWidth())
        self.groupBox_11.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName("groupBox_11")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.groupBox_11)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.pushButton_17 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_17.setObjectName("pushButton_17")
        self.verticalLayout_10.addWidget(self.pushButton_17)
        self.spacer1_2 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer1_2.sizePolicy().hasHeightForWidth())
        self.spacer1_2.setSizePolicy(sizePolicy)
        self.spacer1_2.setText("")
        self.spacer1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spacer1_2.setObjectName("spacer1_2")
        self.verticalLayout_10.addWidget(self.spacer1_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_18 = QtWidgets.QLabel(self.groupBox_11)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_13.addWidget(self.label_18)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_13.addWidget(self.lineEdit_2)
        self.verticalLayout_10.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_19 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_19.setObjectName("pushButton_19")
        self.horizontalLayout_14.addWidget(self.pushButton_19)
        self.label_13 = QtWidgets.QLabel(self.groupBox_11)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_14.addWidget(self.label_13)
        self.verticalLayout_10.addLayout(self.horizontalLayout_14)
        self.spacer2_2 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer2_2.sizePolicy().hasHeightForWidth())
        self.spacer2_2.setSizePolicy(sizePolicy)
        self.spacer2_2.setText("")
        self.spacer2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spacer2_2.setObjectName("spacer2_2")
        self.verticalLayout_10.addWidget(self.spacer2_2)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.label_15 = QtWidgets.QLabel(self.groupBox_11)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_15.addWidget(self.label_15)
        self.textEdit = QtWidgets.QTextEdit(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setObjectName("textEdit")
        self.horizontalLayout_15.addWidget(self.textEdit)
        self.verticalLayout_10.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.pushButton_20 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_20.setObjectName("pushButton_20")
        self.horizontalLayout_16.addWidget(self.pushButton_20)
        self.label_16 = QtWidgets.QLabel(self.groupBox_11)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_16.addWidget(self.label_16)
        self.verticalLayout_10.addLayout(self.horizontalLayout_16)
        self.spacer3_2 = QtWidgets.QLabel(self.groupBox_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spacer3_2.sizePolicy().hasHeightForWidth())
        self.spacer3_2.setSizePolicy(sizePolicy)
        self.spacer3_2.setText("")
        self.spacer3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.spacer3_2.setObjectName("spacer3_2")
        self.verticalLayout_10.addWidget(self.spacer3_2)
        self.pushButton_21 = QtWidgets.QPushButton(self.groupBox_11)
        self.pushButton_21.setObjectName("pushButton_21")
        self.verticalLayout_10.addWidget(self.pushButton_21)
        self.horizontalLayout_10.addWidget(self.groupBox_11)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.groupBox_6 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setBaseSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setObjectName("groupBox_6")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.groupBox_6)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_19 = QtWidgets.QLabel(self.groupBox_6)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_18.addWidget(self.label_19)
        self.pushButton_18 = QtWidgets.QPushButton(self.groupBox_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_18.sizePolicy().hasHeightForWidth())
        self.pushButton_18.setSizePolicy(sizePolicy)
        self.pushButton_18.setObjectName("pushButton_18")
        self.horizontalLayout_18.addWidget(self.pushButton_18)
        self.horizontalLayout_17.addWidget(self.groupBox_6)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setBaseSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName("groupBox_7")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_7)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_19.addWidget(self.label_20)
        self.pushButton_22 = QtWidgets.QPushButton(self.groupBox_7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_22.sizePolicy().hasHeightForWidth())
        self.pushButton_22.setSizePolicy(sizePolicy)
        self.pushButton_22.setObjectName("pushButton_22")
        self.horizontalLayout_19.addWidget(self.pushButton_22)
        self.horizontalLayout_17.addWidget(self.groupBox_7)
        self.verticalLayout_16.addLayout(self.horizontalLayout_17)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.groupBox_8 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_8.setFont(font)
        self.groupBox_8.setObjectName("groupBox_8")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.listWidget = QtWidgets.QListWidget(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_22.addWidget(self.listWidget)
        self.label_23 = QtWidgets.QLabel(self.groupBox_8)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_22.addWidget(self.label_23)
        self.verticalLayout_12.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.pushButton_23 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_23.sizePolicy().hasHeightForWidth())
        self.pushButton_23.setSizePolicy(sizePolicy)
        self.pushButton_23.setObjectName("pushButton_23")
        self.horizontalLayout_23.addWidget(self.pushButton_23)
        self.pushButton_24 = QtWidgets.QPushButton(self.groupBox_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_24.sizePolicy().hasHeightForWidth())
        self.pushButton_24.setSizePolicy(sizePolicy)
        self.pushButton_24.setObjectName("pushButton_24")
        self.horizontalLayout_23.addWidget(self.pushButton_24)
        self.verticalLayout_12.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_20.addWidget(self.groupBox_8)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.groupBox_14 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName("groupBox_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.groupBox_14)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.pushButton_25 = QtWidgets.QPushButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_25.sizePolicy().hasHeightForWidth())
        self.pushButton_25.setSizePolicy(sizePolicy)
        self.pushButton_25.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_25.setObjectName("pushButton_25")
        self.horizontalLayout_24.addWidget(self.pushButton_25)
        self.pushButton_26 = QtWidgets.QPushButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_26.sizePolicy().hasHeightForWidth())
        self.pushButton_26.setSizePolicy(sizePolicy)
        self.pushButton_26.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_26.setObjectName("pushButton_26")
        self.horizontalLayout_24.addWidget(self.pushButton_26)
        self.pushButton_27 = QtWidgets.QPushButton(self.groupBox_14)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_27.sizePolicy().hasHeightForWidth())
        self.pushButton_27.setSizePolicy(sizePolicy)
        self.pushButton_27.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_27.setObjectName("pushButton_27")
        self.horizontalLayout_24.addWidget(self.pushButton_27)
        self.verticalLayout_14.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.label_24 = QtWidgets.QLabel(self.groupBox_14)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_25.addWidget(self.label_24)
        self.comboBox = QtWidgets.QComboBox(self.groupBox_14)
        self.comboBox.setObjectName("comboBox")
        self.horizontalLayout_25.addWidget(self.comboBox)
        self.verticalLayout_14.addLayout(self.horizontalLayout_25)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.checkBox = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_13.addWidget(self.checkBox)
        self.checkBox_2 = QtWidgets.QCheckBox(self.groupBox_14)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_13.addWidget(self.checkBox_2)
        self.verticalLayout_14.addLayout(self.verticalLayout_13)
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.radioButton = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_26.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.groupBox_14)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_26.addWidget(self.radioButton_2)
        self.verticalLayout_14.addLayout(self.horizontalLayout_26)
        self.verticalLayout_11.addWidget(self.groupBox_14)
        self.groupBox_15 = QtWidgets.QGroupBox(self.tab)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName("groupBox_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.groupBox_15)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.label_25 = QtWidgets.QLabel(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMinimumSize(QtCore.QSize(0, 30))
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_27.addWidget(self.label_25)
        self.label_26 = QtWidgets.QLabel(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_26.sizePolicy().hasHeightForWidth())
        self.label_26.setSizePolicy(sizePolicy)
        self.label_26.setMinimumSize(QtCore.QSize(0, 30))
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_27.addWidget(self.label_26)
        self.verticalLayout_15.addLayout(self.horizontalLayout_27)
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.label_28 = QtWidgets.QLabel(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMinimumSize(QtCore.QSize(0, 30))
        self.label_28.setObjectName("label_28")
        self.horizontalLayout_28.addWidget(self.label_28)
        self.label_27 = QtWidgets.QLabel(self.groupBox_15)
        self.label_27.setMinimumSize(QtCore.QSize(0, 30))
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_28.addWidget(self.label_27)
        self.verticalLayout_15.addLayout(self.horizontalLayout_28)
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.label_29 = QtWidgets.QLabel(self.groupBox_15)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setObjectName("label_29")
        self.horizontalLayout_29.addWidget(self.label_29)
        self.label_30 = QtWidgets.QLabel(self.groupBox_15)
        self.label_30.setObjectName("label_30")
        self.horizontalLayout_29.addWidget(self.label_30)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        self.verticalLayout_11.addWidget(self.groupBox_15)
        self.horizontalLayout_20.addLayout(self.verticalLayout_11)
        self.verticalLayout_16.addLayout(self.horizontalLayout_20)
        self.tabWidget.addTab(self.tab, "")
        self.verticalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 26))
        self.menubar.setObjectName("menubar")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionChange_Color = QtWidgets.QAction(MainWindow)
        self.actionChange_Color.setObjectName("actionChange_Color")
        self.actionChange_picture_Size = QtWidgets.QAction(MainWindow)
        self.actionChange_picture_Size.setObjectName("actionChange_picture_Size")
        self.actionSet_Default_Path = QtWidgets.QAction(MainWindow)
        self.actionSet_Default_Path.setObjectName("actionSet_Default_Path")
        self.actionSet_Custom_Colour = QtWidgets.QAction(MainWindow)
        self.actionSet_Custom_Colour.setObjectName("actionSet_Custom_Colour")
        self.actionSet_Tracking_Rate = QtWidgets.QAction(MainWindow)
        self.actionSet_Tracking_Rate.setObjectName("actionSet_Tracking_Rate")
        self.actionSearch = QtWidgets.QAction(MainWindow)
        self.actionSearch.setObjectName("actionSearch")
        self.actionHow_to_use = QtWidgets.QAction(MainWindow)
        self.actionHow_to_use.setObjectName("actionHow_to_use")
        self.actionInfo = QtWidgets.QAction(MainWindow)
        self.actionInfo.setObjectName("actionInfo")
        self.actionFeedback = QtWidgets.QAction(MainWindow)
        self.actionFeedback.setObjectName("actionFeedback")
        self.actionCredits = QtWidgets.QAction(MainWindow)
        self.actionCredits.setObjectName("actionCredits")
        self.actionContact = QtWidgets.QAction(MainWindow)
        self.actionContact.setObjectName("actionContact")
        self.menuSettings.addAction(self.actionChange_Color)
        self.menuSettings.addAction(self.actionChange_picture_Size)
        self.menuSettings.addAction(self.actionSet_Default_Path)
        self.menuSettings.addAction(self.actionSet_Custom_Colour)
        self.menuSettings.addAction(self.actionSet_Tracking_Rate)
        self.menuHelp.addAction(self.actionSearch)
        self.menuHelp.addAction(self.actionHow_to_use)
        self.menuAbout.addAction(self.actionInfo)
        self.menuAbout.addAction(self.actionFeedback)
        self.menuAbout.addAction(self.actionCredits)
        self.menuAbout.addAction(self.actionContact)
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Auducator"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Book"))
        self.label_7.setText(_translate("MainWindow", "Book1"))
        self.pushButton.setText(_translate("MainWindow", "Select"))
        self.pushButton_4.setText(_translate("MainWindow", "New"))
        self.pushButton_5.setText(_translate("MainWindow", "Delete"))
        self.groupBox_10.setTitle(_translate("MainWindow", "Chapter"))
        self.label_8.setText(_translate("MainWindow", "Default"))
        self.pushButton_3.setText(_translate("MainWindow", "Select"))
        self.pushButton_6.setText(_translate("MainWindow", "New"))
        self.pushButton_7.setText(_translate("MainWindow", "Delete"))
        self.groupBox_12.setTitle(_translate("MainWindow", "Pages"))
        self.pushButton_2.setText(_translate("MainWindow", "Delete Page"))
        self.pushButton_8.setText(_translate("MainWindow", "New Page"))
        self.label_10.setText(_translate("MainWindow", "Page Preview"))
        self.groupBox_13.setTitle(_translate("MainWindow", "Labels"))
        self.pushButton_16.setText(_translate("MainWindow", "Delete Label"))
        self.label_11.setText(_translate("MainWindow", "Label Preview"))
        self.groupBox_11.setTitle(_translate("MainWindow", "Label Creation"))
        self.pushButton_17.setText(_translate("MainWindow", "Add New Label"))
        self.label_18.setText(_translate("MainWindow", "Label : "))
        self.pushButton_19.setText(_translate("MainWindow", "Select Audio File"))
        self.label_13.setText(_translate("MainWindow", "No File Selected"))
        self.label_15.setText(_translate("MainWindow", "Description"))
        self.pushButton_20.setText(_translate("MainWindow", "Select Audio File"))
        self.label_16.setText(_translate("MainWindow", "No File Selected"))
        self.pushButton_21.setText(_translate("MainWindow", "Save Label"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Create Book"))
        self.groupBox_6.setTitle(_translate("MainWindow", "Book"))
        self.label_19.setText(_translate("MainWindow", "Book1"))
        self.pushButton_18.setText(_translate("MainWindow", "Select"))
        self.groupBox_7.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_20.setText(_translate("MainWindow", "Default"))
        self.pushButton_22.setText(_translate("MainWindow", "Select"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Pages"))
        self.label_23.setText(_translate("MainWindow", "Page Preview"))
        self.pushButton_23.setText(_translate("MainWindow", "Auto Play"))
        self.pushButton_24.setText(_translate("MainWindow", "Play Page"))
        self.groupBox_14.setTitle(_translate("MainWindow", "Tracking Option"))
        self.pushButton_25.setText(_translate("MainWindow", "Test Color Detection"))
        self.pushButton_26.setText(_translate("MainWindow", "Test Page Detection"))
        self.pushButton_27.setText(_translate("MainWindow", "View Finder"))
        self.label_24.setText(_translate("MainWindow", "Voice Speed"))
        self.checkBox.setText(_translate("MainWindow", "View Tracking"))
        self.checkBox_2.setText(_translate("MainWindow", "GAME MODE"))
        self.radioButton.setText(_translate("MainWindow", "MALE Voice"))
        self.radioButton_2.setText(_translate("MainWindow", "FEMALE Voice"))
        self.groupBox_15.setTitle(_translate("MainWindow", "Now Playing"))
        self.label_25.setText(_translate("MainWindow", "PAGE : "))
        self.label_26.setText(_translate("MainWindow", "Yolo"))
        self.label_28.setText(_translate("MainWindow", "LABEL : "))
        self.label_27.setText(_translate("MainWindow", "Lol"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Play Book"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionChange_Color.setText(_translate("MainWindow", "Change Colour"))
        self.actionChange_picture_Size.setText(_translate("MainWindow", "Change picture Size"))
        self.actionSet_Default_Path.setText(_translate("MainWindow", "Set Default Path"))
        self.actionSet_Custom_Colour.setText(_translate("MainWindow", "Set Custom Colour"))
        self.actionSet_Tracking_Rate.setText(_translate("MainWindow", "Set Tracking Rate"))
        self.actionSearch.setText(_translate("MainWindow", "Search"))
        self.actionHow_to_use.setText(_translate("MainWindow", "How to use"))
        self.actionInfo.setText(_translate("MainWindow", "Info"))
        self.actionFeedback.setText(_translate("MainWindow", "Feedback"))
        self.actionCredits.setText(_translate("MainWindow", "Credits"))
        self.actionContact.setText(_translate("MainWindow", "Contact"))

